### ISSUE TITLE
bug of remove salts function

### ISSUE THREAD

**Issue by greatlse** [PatWalters/transformer#1]
def remove_salts(mol):
    """
    Remove everything but the largest fragment
    :param mol: input molecule
    :return: largest fragment as a molecule
    """
    frags = Chem.GetMolFrags(mol, asMols=True)
    largest = -1
    largest_frag = None
    for frag in frags:
        num_atoms = frag.GetNumAtoms()
        if num_atoms > largest:
            largest_frag = frag
    return largest_frag

this function return the last frag in frags.

**Comment by PatWalters** [comment]
fixed, thanks for pointing this out, apologies for the hassle
